### ISSUE TITLE
FIX: Update Binder link

### ISSUE THREAD

**Issue by josephmje** [carpentries-incubator/SDC-BIDS-dMRI#93]
As @kaitj noticed, the current Binder link is out of date and points to my fork of the repository. I think this must have happened while we were transferring the repository from the CONP repo to mine and then to the Carpentries incubator.

I will update the link but I also noticed that we switched from using the `gh-pages` branch to build the website to the `master` branch. I have no preference on which branch to stick with. But if we're keeping the `master` branch, should we get rid of the `gh-pages` branch to avoid any confusion?

**Comment by jhlegarreta** [comment]
As for the `master` vs. `gh-pages` I wouldn't know to tell advantages/downsides to either solution. Not sure when that change was introduced, but we can revert it if necessary. We have netlify as a check for our changes, so that is already a security measure to prevent changes that prevent the site from being built from being merged in to `master` with some honorable exceptions like the one we experienced this week with the picture location placeholder. But using `gh-pages` as a sort of release branch to build the website makes sense; we just need to either remember merging the `master` changes to it regularly or add that step to the CIs if the builds (provided that we get them working properly) are passing.

**Comment by josephmje** [comment]
I don't think there'd be a big advantage to using either. Traditionally, the `gh-pages` branch is used by GitHub to deploy a website but this can be changed manually in the Settings tab.

Perhaps having a separate branch that only includes the `data`, `fig` and `code` folders could come in handy for building the Binder environment. That way, it would reduce clutter and avoid all of the unnecessary files required for the website. But I can also see this strategy being a bit more burdensome to maintain.

**Comment by kaitj** [comment]
I'm okay with removing `gh-pages` as long as there isn't a carpentries-related reason to keeping it. As @jhlegarreta mentioned, we do have the netlify builds to check for changes. 

I believe the `fig` directory is also home to the figures used in the episodes, so probably want to keep that. I'm not sure about the `data`/`code`/ folders as a separate branch because of the maintenance, though if that can be automated via actions than I am all for it. There is not much within the data directory anyways as we are downloading the data from osf.

**Comment by kaitj** [comment]
I believe the binder link issue was resolved by #108?
